spring.application.name=ticket-tracking-system

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_db
spring.datasource.username=hyfuser
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
